# Generated by Django 5.0.3 on 2024-03-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_seller_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
